language: node_js
sudo: false
dist: trusty

node_js:
  - "8"

cache:
  directories:
    - node_modules

git:
  depth: 10

jobs:
  include:
    - stage: Static Test
      env:
        - test: Editor Config check
      script:
      - echint verbose $(git ls-files)
    - stage: Static Test
      env:
        - test: jscs coding style check
      script:
      - jscs $(git ls-files "*.js")
